spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aeroclub
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-root.yaml